version: '2'

services:
  app:
    build:
      context: .
    image: "shopping/app"
    ports:
      - "8080:8080"
    link:
      - db
    environment:
      - SPRING_MAIL_HOST=host.docker.internal
      - SPRING_JPA_SHOW-SQL=false
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create

  db:
    image: postgres:10.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shopping_postgres
